/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Listar;

import Control.TTipo_Actividad;
import Modificar.Modificar_Tipo_Actividad;
import Negocio.Tipo_Actividad;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
/**
 *
 * @author Daniel Barraza
 */
public class Listar_Tipo_Actividad extends javax.swing.JFrame {

    TTipo_Actividad ttipo_suceso;
   
    public Listar_Tipo_Actividad() {
        initComponents();
       this.setLocationRelativeTo(null);
        ttipo_suceso=new TTipo_Actividad();
        Listar_Tipo_Actividad();
        
        
        
        
    }
    //Listar todos Los Tipo de Actividad
    private void Listar_Tipo_Actividad(){
        DefaultTableModel modelo= (DefaultTableModel) table_lista_suceso.getModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        for(Tipo_Actividad tipo_suceso : ttipo_suceso.listarTipo_Actividad()){
           Object rowData[]={tipo_suceso.getCod_tipo_suceso(),tipo_suceso.getNombre_tipo_suceso()};
           ((DefaultTableModel)table_lista_suceso.getModel()).addRow(rowData);
           }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_lista_suceso = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Listar Tipo Actividad");

        table_lista_suceso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_lista_suceso.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_lista_suceso.getTableHeader().setResizingAllowed(false);
        table_lista_suceso.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table_lista_suceso);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar Tipo Actividad Seleccionada");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       //valida si se seleciono alguna fila dela tabla
        if(table_lista_suceso.getSelectedRow()>=0) {
            //verifica si la ventana se encuentra abierta
           if(Modificar_Tipo_Actividad.ventana_modificar_tipo_suceso==false){
        Modificar_Tipo_Actividad modificar_tipo_suceso=new Modificar_Tipo_Actividad();
        String nro_tipo_suc=String.valueOf(table_lista_suceso.getValueAt(table_lista_suceso.getSelectedRow(),0));
          String nom_tipo_suc=String.valueOf(table_lista_suceso.getValueAt(table_lista_suceso.getSelectedRow(),1));
       modificar_tipo_suceso.modificar_tipo_proyecto(nro_tipo_suc, nom_tipo_suc);
       Modificar_Tipo_Actividad.ventana_modificar_tipo_suceso=true;//cambia el valor de la variable en la siguente ventana
        dispose();
           }
           else{
               JOptionPane.showMessageDialog(null,"VENTANA MODIFICAR TIPO SUCESO SE ENCUENTRA ABIERTA",
            "AVISO DE SISTEMA", JOptionPane.PLAIN_MESSAGE);
           }
           }
       else{
           JOptionPane.showMessageDialog(null,"PORFAVOR SELECCIONE UN TIPO DE SUCESO",
            "AVISO DE SISTEMA", JOptionPane.PLAIN_MESSAGE);
       }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     */
    public void listar_tipo_suceso() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listar_Tipo_Actividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listar_Tipo_Actividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listar_Tipo_Actividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listar_Tipo_Actividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listar_Tipo_Actividad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_lista_suceso;
    // End of variables declaration//GEN-END:variables
}
