/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Listar;

import Control.TTipo_Proyecto;
import Modificar.Modificar_Tipo_Proyecto;
import Negocio.Tipo_Proyecto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
 /**
 *
 * @author Daniel Barraza
 */   
    


public class Listar_Tipo_Proyecto extends javax.swing.JFrame {

    TTipo_Proyecto ttipo_proyecto;
    
    public Listar_Tipo_Proyecto() {
        initComponents();
        this.setLocationRelativeTo(null);
        ttipo_proyecto=new TTipo_Proyecto();
       Listar_Sector();
   
    
    
    
    
    }
    //Listar todos los Sector
    private void Listar_Sector(){
        
        DefaultTableModel modelo= (DefaultTableModel) table_tipo_proyecto.getModel();
        modelo.addColumn("Numero");
        modelo.addColumn("Nombre");
        for(Tipo_Proyecto tipo_ptoyecto : ttipo_proyecto.listarTipoProyecto()){
           Object rowData[]={tipo_ptoyecto.getNro_tipo_proyecto(),tipo_ptoyecto.getNombre_tipo_proyecto()};
           ((DefaultTableModel)table_tipo_proyecto.getModel()).addRow(rowData);
           }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_tipo_proyecto = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listar Tipo Proyecto");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Listar Tipo Proyecto");

        table_tipo_proyecto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_tipo_proyecto.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_tipo_proyecto.getTableHeader().setResizingAllowed(false);
        table_tipo_proyecto.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table_tipo_proyecto);

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar el Tipo de Proyecto Seleccionado ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         //valida si se seleciono alguna fila de la tabla
        if(table_tipo_proyecto.getSelectedRow()>=0) {
             //verifica si la ventana se encuentra abierta
            if(Modificar_Tipo_Proyecto.ventana_modificar_tipo_proyecto==false){
        Modificar_Tipo_Proyecto modificar_tipo_proyecto=new Modificar_Tipo_Proyecto();
        String nro_tipo_pro=String.valueOf(table_tipo_proyecto.getValueAt(table_tipo_proyecto.getSelectedRow(),0));
          String nom__tipo_pro=String.valueOf(table_tipo_proyecto.getValueAt(table_tipo_proyecto.getSelectedRow(),1));
        modificar_tipo_proyecto.modificar_tipo_proyecto(nro_tipo_pro,nom__tipo_pro);
         Modificar_Tipo_Proyecto.ventana_modificar_tipo_proyecto=true;//cambia el valor de la variable en la siguente ventana
        dispose();
            }
            else{
                JOptionPane.showMessageDialog(null,"VENTANA MODIFICAR TIPO PROYECTO SE ENCUENTRA ABIERTA",
            "AVISO DE SISTEMA", JOptionPane.PLAIN_MESSAGE);
            }
            }
        else{
            JOptionPane.showMessageDialog(null,"PORFAVOR SELECCIONE UN TIPO DE PROYECTO",
            "AVISO DE SISTEMA", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void listar_tipo_proyecto() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listar_Tipo_Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listar_Tipo_Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listar_Tipo_Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listar_Tipo_Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listar_Tipo_Proyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_tipo_proyecto;
    // End of variables declaration//GEN-END:variables
}
