/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Registros;

import Validacion.Validar;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.ImageIcon;
/**
 *
 * @author Daniel Barraza
 */
public class Respaldo_DB extends javax.swing.JFrame {

    public static boolean ventana_respaldo = false;
    public Respaldo_DB() {
        initComponents();
        text_mayus.setVisible(false);
        this.setLocationRelativeTo(null);
       
       
    }
    //metodo para enciar informacion al metodo de respaldo de base de datos
    private void respaldar(){
        if (text_ruta.getText().length() != 0) {//valida ubicacion vacia
            Gestion_DB respaldo = new Gestion_DB();
            Validar encrip = new Validar();
            boolean res = false;
            String user = "root";
            String pass = "system";
            String database = "coves_proyectos";
            String contra="2rD/T/RtzHMtkyc/u4fO5Q==";//contraseña maestra encriptada
            try {
            if(contra.equals(encrip.encrypt(text_contra.getText())) && text_contra.getText().length()!=0 ){//valida contraseña maestra
            
                res = respaldo.Respaldar_DB(user, pass, database, text_ruta.getText());
                
            
            if (res) {
                JOptionPane.showMessageDialog(null, "RESPALDO REALIZADO CORRECTAMENTE",
                        "AVISO DE SISTEMA", JOptionPane.PLAIN_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "RESPALDO PERDIDO O SERVIDOR CAIDO",
                        "AVISO DE SISTEMA", JOptionPane.ERROR_MESSAGE);
            }
            }else{
                  JOptionPane.showMessageDialog(null, "CONTRASEÑA MAESTRA INCORRECTA O NO INGRESADA, PORFAVOR COMUNICARSE CON EL ADMINISTRADOR DEL SISTEMA",
                                           "AVISO DE SISTEMA", JOptionPane.ERROR_MESSAGE);  
                    }
        }catch (Exception ex) {
                Logger.getLogger(Respaldo_DB.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else {
            JOptionPane.showMessageDialog(null, "PORFAVOR SELECCIONAR RUTA DE GUARDADO",
                    "AVISO DE SISTEMA", JOptionPane.PLAIN_MESSAGE);
        }
            
    }
    //metodo que permite la seleccion de un archivo
    private void seleccionar_Archivo(){
       //carga la interfaz de archivos, para capturarla ruta
        javax.swing.JFileChooser jF1 = new javax.swing.JFileChooser();
        String ruta = "";
        jF1.setDialogTitle("Seleccionar Nombre para Respaldo...");
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.SQL", "sql");
        jF1.setAcceptAllFileFilterUsed(false);
         //Le indicamos el filtro
        jF1.setFileFilter(filtro);
        try {
            if (jF1.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                ruta = jF1.getSelectedFile().getAbsolutePath();
                //asignas la ruta a un jtextfield
                text_ruta.setText(ruta);
            }
        } catch (HeadlessException ex) {
            ex.getMessage();
        }
        
}
    public void cerrar(){
        
        this.dispose();
            
        }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        boton_respaldar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        text_ruta = new javax.swing.JTextField();
        boton_seleccionar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        text_mayus = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        text_contra = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Respado bd");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Respaldar Base de datos");

        boton_respaldar.setText("Respaldar");
        boton_respaldar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_respaldarActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        text_ruta.setEditable(false);

        boton_seleccionar.setText("Seleccionar...");
        boton_seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_seleccionarActionPerformed(evt);
            }
        });

        jLabel2.setText("Seleccione donde desea guardar el respaldo");

        text_mayus.setText("Tecla mayuscula activada");

        jLabel4.setText("Contraseña Maestra:");

        text_contra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_contraKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jButton2)
                                .addGap(63, 63, 63)
                                .addComponent(boton_respaldar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(text_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boton_seleccionar))
                            .addComponent(text_mayus))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_contra, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_seleccionar))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(text_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_mayus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(boton_respaldar))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_respaldarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_respaldarActionPerformed
        
        
        File file=new File(text_ruta.getText());
        if(file.exists()){//verifica si erchivo existe, en caso de existir confirmará su reemplazo
            int resp = JOptionPane.showConfirmDialog(null, "¿REALMENTE DESEA REEMPLAZAR EL ARCHIVO?", "ALERTA!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
            if(resp==0){
               respaldar(); 
            }else{
                seleccionar_Archivo();
            }
        } else{
                respaldar();
        }
    }//GEN-LAST:event_boton_respaldarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        ventana_respaldo = false;//vuelve los campos a sus estado inicial, al cerrar la ventana
    }//GEN-LAST:event_formWindowClosed

    private void boton_seleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_seleccionarActionPerformed
        seleccionar_Archivo();
    }//GEN-LAST:event_boton_seleccionarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //temporizador de interfaz, que se cierra automaticamente a los 10min
        Timer timer = new Timer (60000, new ActionListener ()
{
           int con=0;
           
          @Override
          public void actionPerformed(ActionEvent e) {
              
              
              con=con+1;
              if(con==10){
                  JOptionPane.showMessageDialog(null, "TIEMPO DE ESPERA PARA REALIZAR EL RESPALDO TERMINADO, LA INTERFAZ FUE CERRADA",
                    "AVISO DE SISTEMA", JOptionPane.PLAIN_MESSAGE);
                  cerrar();

                  
              }
              
          }
      });
            
        timer.start();
    }//GEN-LAST:event_formWindowOpened

    private void text_contraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_contraKeyReleased
        boolean capsActivo = Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK);
       text_mayus.setVisible(capsActivo);
    }//GEN-LAST:event_text_contraKeyReleased

    /**
     */
    public void respaldo_db() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Respaldo_DB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Respaldo_DB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Respaldo_DB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Respaldo_DB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Respaldo_DB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_respaldar;
    private javax.swing.JButton boton_seleccionar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField text_contra;
    private javax.swing.JLabel text_mayus;
    private javax.swing.JTextField text_ruta;
    // End of variables declaration//GEN-END:variables
}
